export interface ValidateAddressInterface {
  /**
   * If the address is valid or not. If not, this is the only property returned.
   *
   * @type {boolean}
   */
  isvalid: boolean;
  /**
   * The bitcoin address validated
   *
   * @type {string}
   */
  address: string;
  /**
   * The hex-encoded scriptPubKey generated by the address
   *
   * @type {string}
   */
  scriptPubKey: string;
  /**
   * If the key is a script
   *
   * @type {boolean}
   */
  isscript: boolean;
  /**
   * If the address is a witness address
   *
   * @type {boolean}
   */
  iswitness: boolean;
  /**
   * The version number of the witness program
   *
   * @type {number}
   */
  witness_version?: number;
  /**
   * The hex value of the witness program
   *
   * @type {string}
   */
  witness_program?: string;
}
