name: Publish Module on NPM

on:
  release:
    types: [ created ]

env:
  RPC_USER: rpcuser
  RPC_PASS: rpcpass
  RPC_PORT: 8332
jobs:
  testing:
    name: "Testing"
    uses: ./.github/workflows/testing.yml
  publish-npm:
    name: "Publishing on NPM"
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm i
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
